<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RL948I0" name="testApparent.TC_Apparent" tests="4" failures="0" timestamp="2 Mar 2021 14:41:54 GMT" time="2.525" errors="4">
  <testcase name="TC005" time="0.014" classname="testApparent.TC_Apparent">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.aventstack.extentreports.Report.lambda$createTest$0(Report.java:68)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.aventstack.extentreports.Report.createTest(Report.java:68)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:230)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:243)
	at resources.Reporter.<init>(Reporter.java:27)
	at resources.Testing.<init>(Testing.java:30)
	at testApparent.TC_Apparent.TC005(TC_Apparent.java:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- TC005 -->
  <testcase name="TC002" time="1.251" classname="testApparent.TC_Apparent">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.aventstack.extentreports.Report.lambda$createTest$0(Report.java:68)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.aventstack.extentreports.Report.createTest(Report.java:68)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:230)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:243)
	at resources.Reporter.<init>(Reporter.java:27)
	at resources.Testing.<init>(Testing.java:30)
	at testApparent.TC_Apparent.TC002(TC_Apparent.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- TC002 -->
  <testcase name="TC004" time="0.009" classname="testApparent.TC_Apparent">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.aventstack.extentreports.Report.lambda$createTest$0(Report.java:68)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.aventstack.extentreports.Report.createTest(Report.java:68)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:230)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:243)
	at resources.Reporter.<init>(Reporter.java:27)
	at resources.Testing.<init>(Testing.java:30)
	at testApparent.TC_Apparent.TC004(TC_Apparent.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- TC004 -->
  <testcase name="TC003" time="1.251" classname="testApparent.TC_Apparent">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.aventstack.extentreports.Report.lambda$createTest$0(Report.java:68)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.aventstack.extentreports.Report.createTest(Report.java:68)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:230)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:243)
	at resources.Reporter.<init>(Reporter.java:27)
	at resources.Testing.<init>(Testing.java:30)
	at testApparent.TC_Apparent.TC003(TC_Apparent.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- TC003 -->
</testsuite> <!-- testApparent.TC_Apparent -->
